CREATE TABLE mh_company
(
    ID          bigint generated by default as identity (start with 1) PRIMARY KEY,
    VERSION     NUMERIC(5, 0) NOT NULL,
    NAME        VARCHAR(100)   NOT NULL
);

insert into mh_company
(version, name)
VALUES
(0, 'Company #1');